site_name: Lab Equipment Booking
theme: mkdocs-material
nav:
  - Home: index.md
  - Equipment:
      - Cobalt Traffic Controller: equipment/Cobalt Traffic Controller.md
      - EVO Radar: equipment/EVO Radar.md
      - Flir TrafiSense AI: equipment/Flir TrafiSense AI.md
      - Four-legged Robot Spot: equipment/Four-legged Robot Spot.md
      - Husky A300: equipment/Husky A300.md
      - Mikado Soundcam: equipment/Mikado Soundcam.md
      - Neousys NRU-220S Series: equipment/Neousys NRU-220S Series.md
      - Parrot ANAFI Ai: equipment/Parrot ANAFI Ai.md
      - Traction Plus Motion Simulator Platform: equipment/Traction Plus Motion Simulator Platform.md
      - virtual reality slimx-13: equipment/virtual reality slimx-13.md